import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:flutter/foundation.dart';

/// Firebase Service
/// Handles Firebase initialization and error reporting
class FirebaseService {
  static FirebaseAnalytics? _analytics;
  static FirebaseAnalyticsObserver? _observer;

  /// Initialize Firebase
  static Future<void> initialize() async {
    await Firebase.initializeApp(
      // Options will be generated by FlutterFire CLI
      // Run: flutterfire configure
    );

    // Initialize Crashlytics (non-web only)
    if (!kIsWeb) {
      // Pass all uncaught errors to Crashlytics
      FlutterError.onError = (errorDetails) {
        FirebaseCrashlytics.instance.recordFlutterFatalError(errorDetails);
      };

      // Pass all uncaught asynchronous errors
      PlatformDispatcher.instance.onError = (error, stack) {
        FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
        return true;
      };

      // Disable in debug mode
      await FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(
        !kDebugMode,
      );
    }

    // Initialize Analytics
    _analytics = FirebaseAnalytics.instance;
    _observer = FirebaseAnalyticsObserver(analytics: _analytics!);
  }

  /// Get Analytics instance
  static FirebaseAnalytics get analytics {
    if (_analytics == null) {
      throw Exception(
        'Firebase not initialized. Call FirebaseService.initialize() first.',
      );
    }
    return _analytics!;
  }

  /// Get Analytics Observer for navigation tracking
  static FirebaseAnalyticsObserver get observer {
    if (_observer == null) {
      throw Exception(
        'Firebase not initialized. Call FirebaseService.initialize() first.',
      );
    }
    return _observer!;
  }

  /// Log custom event
  static Future<void> logEvent({
    required String name,
    Map<String, Object>? parameters,
  }) async {
    await _analytics?.logEvent(name: name, parameters: parameters);
  }

  /// Set user ID for analytics
  static Future<void> setUserId(String? userId) async {
    await _analytics?.setUserId(id: userId);
    if (!kIsWeb && userId != null) {
      await FirebaseCrashlytics.instance.setUserIdentifier(userId);
    }
  }

  /// Set user property
  static Future<void> setUserProperty({
    required String name,
    required String? value,
  }) async {
    await _analytics?.setUserProperty(name: name, value: value);
  }

  /// Log screen view
  static Future<void> logScreenView({
    required String screenName,
    String? screenClass,
  }) async {
    await _analytics?.logScreenView(
      screenName: screenName,
      screenClass: screenClass,
    );
  }

  /// Log error to Crashlytics
  static Future<void> logError(
    dynamic error,
    StackTrace? stack, {
    String? reason,
    bool fatal = false,
  }) async {
    if (!kIsWeb) {
      await FirebaseCrashlytics.instance.recordError(
        error,
        stack,
        reason: reason,
        fatal: fatal,
      );
    }
    // Also log to console in debug mode
    if (kDebugMode) {
      debugPrint('Error: $error');
      if (stack != null) debugPrint('Stack: $stack');
    }
  }

  /// Add custom log message
  static Future<void> log(String message) async {
    if (!kIsWeb) {
      await FirebaseCrashlytics.instance.log(message);
    }
    if (kDebugMode) {
      debugPrint('[Firebase Log] $message');
    }
  }
}
